name: Release
on: workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build-binary.yaml
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - run: ls -R
