name: Update version
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: "Version of the app to release"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Set new version
      run: |
        echo "${{inputs.version}}" > version

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        default_author: github_actions
        add: version
        message: "Bump to version ${{inputs.version}}"
